name: "prolificdreamer-texture"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [1.0, 1.5]
  fovy_range: [40, 70]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.5
  eval_fovy_deg: 70.
  eval_elevation_deg: 30.

system_type: "prolificdreamer-system"
system:
  eval_vis_shading: true
  stage: texture
  geometry_convert_from: ???
  geometry_type: "tetrahedra-sdf-grid"
  geometry_convert_inherit_texture: true
  geometry:
    radius: 2.0 # consistent with last stage
    isosurface_resolution: 128 # consistent with last stage
    isosurface_deformable_grid: true
    isosurface_remove_outliers: true
    pos_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.381912879967776 # max resolution 2048
      start_level: 16
      start_step: 2000
      update_steps: 500
    # pos_encoding_config:
    #   otype: HashGrid
    #   n_levels: 16
    #   n_features_per_level: 2
    #   log2_hashmap_size: 19
    #   base_resolution: 16
    #   per_level_scale: 1.447269237440378 # max resolution 4096
    fix_geometry: true


  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 0
    albedo_activation: sigmoid
  # material_type: "no-material"
  # material:
  #   n_output_dims: 3
  #   color_activation: sigmoid

  background_type: solid-color-background
  background:
    color: [1.0, 1.0, 1.0]

  # background_type: "neural-environment-map-background"
  # background:
  #   color_activation: sigmoid

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [5000, 0.98, 0.5, 5001] # annealed to 0.5 after 5000 steps

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_vsd: 1.
    lambda_lora: 1.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      guidance:
        lr: 0.0001

trainer:
  max_steps: 30000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
