name: "att3d-if"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 64
  height: 64
  camera_distance_range: [1.5, 2.0]
  fovy_range: [40, 70]
  elevation_range: [-10, 90]
  light_sample_strategy: "dreamfusion"
  eval_camera_distance: 2.0
  eval_fovy_deg: 70.

system_type: "att3d-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 2.0
    normal_type: "analytic"

    # the density initialization proposed in the DreamFusion paper
    # does not work very well
    # density_bias: "blob_dreamfusion"
    # density_activation: exp
    # density_blob_scale: 5.
    # density_blob_std: 0.2

    # use Magic3D density initialization instead
    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    # coarse to fine hash grid encoding
    # to ensure smooth analytic normals
    pos_encoding_config:
      otype: DenseGrid
      n_levels: 5
      n_features_per_level: 4
      base_resolution: 16
      per_level_scale: 1.4142135623730951 # max resolution 64

      # otype: ProgressiveBandHashGrid
      # n_levels: 16
      # n_features_per_level: 2
      # log2_hashmap_size: 19
      # base_resolution: 16
      # per_level_scale: 1.447269237440378 # max resolution 4096
      # start_level: 8 # resolution ~200
      # start_step: 2000
      # update_steps: 500

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 1000
    albedo_activation: scale_-11_01

  background_type: "neural-environment-map-background"
  background:
    color_activation: scale_-11_01
    random_aug: true

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 256
    grid_prune: false

  prompt_processor_type: "deep-floyd-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    prompt: "composite_prompts"
    composite_prompt_dir: ???

  guidance_type: "deep-floyd-guidance"
  guidance:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    guidance_scale: 100.
    weighting_strategy: sds
    min_step_percent: 0.02
    max_step_percent: 0.98

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_orient: 0.0
    lambda_sparsity: 0.0
    lambda_opaque: 0.0
  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.95, 0.999]
      eps: 1.e-15
    params:
      hypernet:
        lr: 0.1
      geometry:
        lr: 0.01
      background:
        lr: 0.001

trainer:
  max_steps: 20000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
