name: "dynamic-gaussian-reconstruct"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "dynamic-multiview-camera-datamodule"
data:
  train_downsample_resolution: 1
  eval_downsample_resolution: 1
  eval_data_interval: 1
  camera_layout: "default"
  initial_t0_step: 2000
  dataroot: ???

system_type: "dynamic-gaussian-splatting-reconstruct-system"
system:

  extent: 1.0
  num_pts: 5000
  invert_bg_prob: 0.5

  geometry_type: "dynamic-gaussian"
  geometry:
    gaussian_name: "gaussian"
    gaussian:
      position_lr_init: 0.00016
      position_lr_final:  0.0000016
      position_lr_delay_mult: 0.01
      position_lr_max_steps: 30000
      feature_lr: 0.0025
      opacity_lr: 0.05
      # opacity_lr: 0.01
      scaling_lr: 0.005
      rotation_lr: 0.001
      percent_dense: 0.01
      densification_interval: 100
      opacity_reset_interval: 2000
      densify_from_iter: 500
      densify_until_iter: 15000
      densify_grad_threshold: 0.0002
      force_sphere: True
    dynamic_flow_name: "dynamic-flow-mlp"
    dynamic_flow_config:
      n_feature_dims: 7
      need_normalization: True


  renderer_type: "dynamic-gaussian-rasterizer"
  renderer:
    debug: false
    invert_bg_prob: 0.5

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  # guidance_type: "stable-diffusion-instructpix2pix-guidance"
  # guidance:
  #   min_step_percent: 0.02
  #   max_step_percent: 0.98

  # guidance_type: "stable-diffusion-controlnet-guidance"
  # guidance:
  #   control_type: "normal"
  #   min_step_percent: 0.05
  #   max_step_percent: 0.8
  #   condition_scale: 1.0
  #   fixed_size: 512
  #   cache_dir: '/root/autodl-tmp/.huggingface_cache'

  # prompt_processor_type: "stable-diffusion-prompt-processor"
  # prompt_processor:
  #   pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
  #   prompt: "Turn him into Elon Musk"

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_l1: 1.0

  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.dynamic_flow:
        lr: 0.0001

trainer:
  max_steps: 30000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  precision: 32-true

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
