name: "dreamfusion-if"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [2.5, 2.5]
  fovy_range: [49.1, 49.1]
  elevation_range: [-80, 80]
  light_sample_strategy: "dreamfusion"
  eval_camera_distance: 2.5
  eval_fovy_deg: 49.1

system_type: "gaussian-splatting-system"
system:
  extent: 1.0
  num_pts: 2000
  invert_bg_prob: 0.5

  geometry_type: "gaussian"
  geometry:
    position_lr_init: 0.0001
    position_lr_final: 0.00002
    position_lr_delay_mult: 0.02
    position_lr_max_steps: 1000
    feature_lr: 0.01
    opacity_lr: 0.05
    scaling_lr: 0.005
    rotation_lr: 0.005
    percent_dense: 0.1
    densification_interval: 100
    prune_interval: 50
    opacity_reset_interval: 100000
    densify_from_iter: 100
    densify_until_iter: 1000
    densify_grad_threshold: 0.02
    min_opac_prune: 0.05

  renderer_type: "diff-gaussian-rasterizer"
  renderer:
    debug: false

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???

  guidance_type: "stable-diffusion-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 50.0
    weighting_strategy: sds
    min_step_percent: 0.02
    max_step_percent: 0.98

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 0.1

trainer:
  max_steps: 4000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 32-true

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
