name: "latentnerf-vsd"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  elevation_range: [-10, 45]

system_type: "latentnerf-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    n_feature_dims: 4
    normal_type: null

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

  material_type: "no-material"
  material:
    n_output_dims: 4
    color_activation: none

  background_type: "neural-environment-map-background"
  background:
    n_output_dims: 4
    color_activation: none

  renderer_type: "nerf-volume-renderer"
  renderer:
    num_samples_per_ray: 512

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [5000, 0.98, 0.5, 5001] # annealed to 0.5 after 5000 steps

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_vsd: 1.
    lambda_lora: 1.
    lambda_sparsity: 5.e-4
    lambda_opaque: 0.0
    lambda_orient: 0.0
  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      background:
        lr: 0.001
      guidance:
        lr: 0.0001

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
